import { PhotoIcon, XCircleIcon } from '@heroicons/react/24/solid'
import { NextPage } from 'next'
import { redirect } from 'next/navigation';
import Head from 'next/head'
import { useState } from 'react'
import { api } from '~/utils/api'

const RegisterPage: NextPage = () => {
    const utils = api.useContext();

    const [username, setUsername] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [avatar, setAvatar] = useState('');

    const { mutate, error } = api.auth.register.useMutation({
        onSuccess() {
            setUsername("");
            setEmail("");
            setPassword("");
            setAvatar("");

            redirect('/dashboard')
        },
    });


    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
                <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
                    <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
                        Create <span className="text-pink-400">Game & Web</span> <span className="text-purple-400">Account</span>
                    </h1>
                    <form>
                        <div className="space-y-12 sm:space-y-16">
                            {error?.message && (<div className="rounded-md bg-red-50 p-4">
                                <div className="flex">
                                    <div className="flex-shrink-0">
                                        <XCircleIcon className="h-5 w-5 text-red-400" aria-hidden="true" />
                                    </div>
                                    <div className="ml-3">
                                        <h3 className="text-sm font-medium text-red-800">{error.data?.code}: {error.message}</h3>
                                        <div className="mt-2 text-sm text-red-700">
                                            <pre>{error.data?.stack}</pre>
                                        </div>
                                    </div>
                                </div>
                            </div>)}

                            <div>
                                <h2 className="text-base font-semibold leading-7 text-purple-400">Game Account</h2>
                                <p className="mt-1 max-w-2xl text-sm leading-6 text-pink-400">
                                    This information will be used for signing into our game servers and web services.
                                </p>

                                <div className="mt-10 space-y-8 border-b border-pink-400/10 pb-12 sm:space-y-0 sm:divide-y sm:divide-pink-400/10 sm:border-t sm:pb-0">
                                    <div className="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:py-6">
                                        <label htmlFor="username" className="block text-sm font-medium leading-6 text-pink-400 sm:pt-1.5">
                                            Username
                                        </label>
                                        <div className="mt-2 sm:col-span-2 sm:mt-0">
                                            <div className="flex rounded-md shadow-sm ring-1 ring-inset ring-pink-300 focus-within:ring-2 focus-within:ring-inset focus-within:ring-purple-600 sm:max-w-md">
                                                <span className="flex select-none items-center pl-3 text-pink-500 sm:text-sm">mwow.host/</span>
                                                <input
                                                    type="text"
                                                    name="username"
                                                    id="username"
                                                    autoComplete="first-name"
                                                    className="block flex-1 border-0 bg-transparent py-1.5 pl-1 text-pink-400 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"
                                                    placeholder="johnyBravo"
                                                    value={username}
                                                    onChange={(e) => setUsername(e.target.value)}
                                                />
                                            </div>
                                            {error?.data?.zodError?.fieldErrors.username && (
                                                <span className="mb-2 text-red-500">
                                                    {error.data.zodError.fieldErrors.username}
                                                </span>
                                            )}
                                        </div>
                                    </div>

                                    <div className="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:py-6">
                                        <label htmlFor="email" className="block text-sm font-medium leading-6 text-pink-400 sm:pt-1.5">
                                            Email address
                                        </label>
                                        <div className="mt-2 sm:col-span-2 sm:mt-0">
                                            <input
                                                id="email"
                                                name="email"
                                                type="email"
                                                autoComplete="email"
                                                className="block w-full rounded-md border-0 py-1.5 text-pink-400 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:max-w-md sm:text-sm sm:leading-6"
                                                value={email}
                                                onChange={(e) => setEmail(e.target.value)}
                                            />
                                            {error?.data?.zodError?.fieldErrors.email && (
                                                <span className="mb-2 text-red-500">
                                                    {error.data.zodError.fieldErrors.email}
                                                </span>
                                            )}
                                        </div>
                                    </div>


                                    <div className="sm:grid sm:grid-cols-3 sm:items-start sm:gap-4 sm:py-6">
                                        <label htmlFor="password" className="block text-sm font-medium leading-6 text-pink-400 sm:pt-1.5">
                                            Password
                                        </label>
                                        <div className="mt-2 sm:col-span-2 sm:mt-0">
                                            <input
                                                id="password"
                                                name="password"
                                                type="password"
                                                autoComplete="new-password"
                                                className="block w-full rounded-md border-0 py-1.5 text-pink-400 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-purple-600 sm:max-w-md sm:text-sm sm:leading-6"
                                                value={password}
                                                onChange={(e) => setPassword(e.target.value)}
                                            />
                                            {error?.data?.zodError?.fieldErrors.password && (
                                                <span className="mb-2 text-red-500">
                                                    {error.data.zodError.fieldErrors.password}
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <h2 className="text-base font-semibold leading-7 text-pink-400">Web User Details</h2>
                                <p className="mt-1 max-w-2xl text-sm leading-6 text-gray-600">
                                    This information will be used for our web services including the forum.
                                </p>

                                <div className="mt-10 space-y-8 border-b border-pink-400/10 pb-12 sm:space-y-0 sm:divide-y sm:divide-pink-400/10 sm:border-t sm:pb-0">
                                    <div className="sm:grid sm:grid-cols-3 sm:items-center sm:gap-4 sm:py-6">
                                        <label htmlFor="photo" className="block text-sm font-medium leading-6 text-pink-400">
                                            Avatar
                                        </label>
                                        <div className="mt-2 sm:col-span-2 sm:mt-0">
                                            <div className="flex items-center gap-x-3">
                                                <PhotoIcon className="h-12 w-12 text-gray-300" aria-hidden="true" />
                                                <button
                                                    type="button"
                                                    className="rounded-md bg-white py-1.5 px-2.5 text-sm font-semibold text-pink-400 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                                                >
                                                    Change
                                                </button>
                                            </div>
                                            {error?.data?.zodError?.fieldErrors.avatar && (
                                                <span className="mb-2 text-red-500">
                                                    {error.data.zodError.fieldErrors.avatar}
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* <div>
                    <h2 className="text-base font-semibold leading-7 text-pink-400">Notifications</h2>
                    <p className="mt-1 max-w-2xl text-sm leading-6 text-gray-600">
                        We'll always let you know about important changes, but you pick what else you want to hear about.
                    </p>

                    <div className="mt-10 space-y-10 border-b border-pink-400/10 pb-12 sm:space-y-0 sm:divide-y sm:divide-pink-400/10 sm:border-t sm:pb-0">
                        <fieldset>
                            <legend className="sr-only">By Email</legend>
                            <div className="sm:grid sm:grid-cols-3 sm:gap-4 sm:py-6">
                                <div className="text-sm font-semibold leading-6 text-pink-400" aria-hidden="true">
                                    By Email
                                </div>
                                <div className="mt-4 sm:col-span-2 sm:mt-0">
                                    <div className="max-w-lg space-y-6">
                                        <div className="relative flex gap-x-3">
                                            <div className="flex h-6 items-center">
                                                <input
                                                    id="comments"
                                                    name="comments"
                                                    type="checkbox"
                                                    className="h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-600"
                                                />
                                            </div>
                                            <div className="text-sm leading-6">
                                                <label htmlFor="comments" className="font-medium text-pink-400">
                                                    Comments
                                                </label>
                                                <p className="mt-1 text-gray-600">Get notified when someones posts a comment on a post you're following'.</p>
                                            </div>
                                        </div>
                                        <div className="relative flex gap-x-3">
                                            <div className="flex h-6 items-center">
                                                <input
                                                    id="candidates"
                                                    name="candidates"
                                                    type="checkbox"
                                                    className="h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-600"
                                                />
                                            </div>
                                            <div className="text-sm leading-6">
                                                <label htmlFor="candidates" className="font-medium text-pink-400">
                                                    Candidates
                                                </label>
                                                <p className="mt-1 text-gray-600">Get notified when a candidate applies for a job.</p>
                                            </div>
                                        </div>
                                        <div className="relative flex gap-x-3">
                                            <div className="flex h-6 items-center">
                                                <input
                                                    id="offers"
                                                    name="offers"
                                                    type="checkbox"
                                                    className="h-4 w-4 rounded border-gray-300 text-purple-600 focus:ring-purple-600"
                                                />
                                            </div>
                                            <div className="text-sm leading-6">
                                                <label htmlFor="offers" className="font-medium text-pink-400">
                                                    Offers
                                                </label>
                                                <p className="mt-1 text-gray-600">Get notified when a candidate accepts or rejects an offer.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <legend className="sr-only">Push Notifications</legend>
                            <div className="sm:grid sm:grid-cols-3 sm:items-baseline sm:gap-4 sm:py-6">
                                <div className="text-sm font-semibold leading-6 text-pink-400" aria-hidden="true">
                                    Push Notifications
                                </div>
                                <div className="mt-1 sm:col-span-2 sm:mt-0">
                                    <div className="max-w-lg">
                                        <p className="text-sm leading-6 text-gray-600">These are delivered via SMS to your mobile phone.</p>
                                        <div className="mt-6 space-y-6">
                                            <div className="flex items-center gap-x-3">
                                                <input
                                                    id="push-everything"
                                                    name="push-notifications"
                                                    type="radio"
                                                    className="h-4 w-4 border-gray-300 text-purple-600 focus:ring-purple-600"
                                                />
                                                <label htmlFor="push-everything" className="block text-sm font-medium leading-6 text-pink-400">
                                                    Everything
                                                </label>
                                            </div>
                                            <div className="flex items-center gap-x-3">
                                                <input
                                                    id="push-email"
                                                    name="push-notifications"
                                                    type="radio"
                                                    className="h-4 w-4 border-gray-300 text-purple-600 focus:ring-purple-600"
                                                />
                                                <label htmlFor="push-email" className="block text-sm font-medium leading-6 text-pink-400">
                                                    Same as email
                                                </label>
                                            </div>
                                            <div className="flex items-center gap-x-3">
                                                <input
                                                    id="push-nothing"
                                                    name="push-notifications"
                                                    type="radio"
                                                    className="h-4 w-4 border-gray-300 text-purple-600 focus:ring-purple-600"
                                                />
                                                <label htmlFor="push-nothing" className="block text-sm font-medium leading-6 text-pink-400">
                                                    No push notifications
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div> */}
                        </div>

                        <div className="mt-6 flex items-center justify-end gap-x-6">
                            <button type="button" className="text-sm font-semibold leading-6 text-pink-400">
                                Cancel
                            </button>
                            <button
                                type="button"
                                className="inline-flex justify-center rounded-md bg-purple-600 py-2 px-3 text-sm font-semibold text-white shadow-sm hover:bg-purple-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-purple-600"
                                onClick={() => mutate({
                                    username,
                                    email,
                                    password,
                                    avatar,
                                })}
                            >
                                Register
                            </button>
                        </div>
                    </form>
                </div>
            </main>
        </>
    );
}

export default RegisterPage;